# Given: A DNA string s of length at most 1000 nt.
# Return: Four integers (separated by spaces) counting the respective number of times that the symbols 'A', 'C', 'G', and 'T' occur in s

# tally the frequency of each nucleotide in 
def countNucFrequency(dna_seq):
    freqDict = {"A": 0, "C": 0, "G": 0, "T": 0}
    for nuc in dna_seq:
        freqDict[nuc] += 1
    return freqDict

dna_str = "TTGAAGCAGAGTTCCCCCGAGTTTATGAACCCGCGGTAAGGATCTAGGATCATCTATTCGATTAAAAAGCTGTCTCACTGGACTCGTAGTTGTATGTCAAGTCTACGGGGCAGATTCCTACCGGCACCGGAACTGTCCCGCAAGCAGGGAACTCCCTCTTATCAGGGTGCGACTGCAAAAATGAGCACTCGGTCGATCAACCCTTGGGAGAGGCGCTACTCATAACAGACCCCAGACTCGCGAAGTTTCTAGAGCGTAGTAATGGGGCCTGTCCAAGCTACAGGGATCTATTGCTACGCTTATAATAGGACTTAGCATTTCGAAGAGCGCTCGGTGACCCGGAGATTTATTCAACCACTATAGTAGGTCACTGCATGGATTTTGAGCGGCGTGACCGATTACAAACCGTTGCTTTGCCCGTACAAGCAACCTTACAGCCCATACGCTCCGTCCCAGGGACAGTAGTTCATGCCGGAAAGAAATAATATTTGATTATGTGTTCTTCCCTGGACGGTTTTAGGTATCACGGCGAAAGGGGGCAAGTCATTCGCGTCGTAGTGAAACGAGTCCGTCATCACCGGTGTCTTAATTGACCACCTGTCTAGACGCAGGTCTCCTACGTAAACCTGGTTGTCGACCACACAGTCCTTCCATAGAGTCCTCGACGCGCGTGCCGGTCCTGCATCTCTGGCTACGCTACCCGCCTTCACGCACGGGAACGTTTTGCCCGTTACGATTCGCTGCCCCCGCAGTGCTCACACGCGCATTGGGGTAGGGAGTTTGCGCAGCCTTTGTCATGCCCGGTTGGATGTCCCACGCGCATGGGGCCTACACTCCTCCGCGATCGCCCATGCCGTATAATGTGCTCATAAGTAGGACCACTCAAGGTCTAGGAACCAGATGCGATTATCCTTAAACGCGGATATACCATCCTAGTATAACTGGTCTACAAAACCTTTGTCTAGCATATTGACCATCC"

nuc_tally = countNucFrequency(dna_str)

print(' '.join([str(val) for key, val in nuc_tally.items()]))
