# The reverse complement of a DNA string s is the string sc formed by reversing the symbols of s, then taking the complement of each symbol (e.g., the reverse complement of "GTCA" is "TGAC").

# Given: A DNA string s of length at most 1000 bp.
# Return: The reverse complement s^c of s.

DNA_reverse_comp_dict = {'A': 'T', 'T': 'A', 'G': 'C', 'C': 'G'}

def reverse_complement(dna_str):
    return ''.join([DNA_reverse_comp_dict[n] for n in dna_str])[::-1]

dna = "CTATAGGACGCAAGGCCCCACGGTTTCTTAGGAAAGTTCGACGTCCAGATGCACCGTTACACTTCGAATTGTCGCCGACTTCTTTCCGCGCGACTGCTTAGGGAAATAAGTCAAAGGACTCCGGTCCAGTAGGGGGCCCTACACGATCATACGCTGTAATTCCACCGCGGCGAGCAAACGTACCGGTGGCTTGTGCCCCGGACTCGTACTGGACGAGAGTACAAGATTCCTGTGCTAGGGATGCTAATACCGATTCATACGGGAATCGTGGTACGATAGATGGGACCAGTATGCGGCTTCTTCGTACAGACCTACCACAACAGGCACTCCCCGGTATGACGATATAAGTTACTCTATTGAAGCGACAATGGTTATCACGCGGATTGAGTCGTCCAAACTACTATGCCCTAATAACTAAGCACACCGGCCTCCTTTACGTGCTACATCTTCAGTAGAGAGCTCGATAGTTAGGCTGAATGACGAGTATGTCGGTCGCATGGAAGTGCAGACAGGGACAACTTAACCACGGAGTGTCTGTTACTGCGGGTGCTCACGTCAGAACAGACTGGAATTACCAGGCCCAGCTACGCTAACTAATTACAGATGAAGGAAACCATTGACTAACATCCAAGGCTTTACGATAGACAAAACATGTTCATCCTGCATGAAAGCGTCGCGCACGCGGAAAACTGATTTTCGATAGACTCTCCATTCATACAGAGTACCACTCAGTGTCTCCGCTTAATGCGCGACTGGACTAATAAGTTCAAGCGCATGAGGCGCCGTATTATGTCTCGACCCAGTGTATTTGAGTCGTAGTCTTTGTAGGCCGATAAAAATCATTATGCAATAGACTGCAACCATTGGATAATTATTGTGATCTATCGCCCAGTAGGCAGTACAGCGATAATACACACATTTGATTGGTAAGCTTGTGGCATCACAGCCCTTTCTACGCCTAC"
print(reverse_complement(dna))
